# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ffc55e51cd646d7d971b431187699835b55426d9efe2e57ebd3e7ea041886309f6b70ede985058304499d21dfdb0059188648d49101eb7f33fbd2ca72d7866

test:
  secret_key_base: d5f6105d3642ad2f0b074faa3d396b3be504502c4c71bc10083c89d119613d895cd0550f928bcabd5599d5b593f7698766a5014e893d4e4f18ba7cdae6b141ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
